version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: sms-app
    restart: unless-stopped
    tty: true
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: app
      DB_USERNAME: app
      DB_PASSWORD: secret
    volumes:
      - ./:/var/www/:cached
    working_dir: /var/www

  #Nginx Service
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    container_name: sms-web
    volumes:
      - ./:/var/www/:cached
    ports:
      - 8080:80

  #MariaDB Service
  db:
    image: mariadb:10.3.8
    volumes:
      - db-data:/var/lib/mysql
    container_name: sms-db
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root

volumes:
  db-data: